eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-primary:8011/eureka/,http://eureka-secondary:8012/eureka/,http://eureka-tertiary:8013/eureka/

---
spring:
  profiles: sujeto
words: Yo,Tu,El,Nosotros,Vosotros,Ellos

---
spring:
  profiles: verbo
words: salta,corre,come,programa,juega,lee

---
spring:
  profiles: articulo
words: el,la,los,las

---
spring:
  profiles: adjetivo
words: lindo,maravilloso,hermoso,grande,perfecto

---
spring:
  profiles: sustantivo
words: gato,bote,computadora,silla,mesa,juguete
